name: 'AI GitHub Action'
description: 'GitHub Actions powered by the OpenAI Agents SDK'
author: 'Aguirre Ibarra'
branding:
  icon: 'cpu'
  color: 'blue'

inputs:
  action-type:
    description: 'Type of action to perform (pr-review, issue-analyze, code-scan)'
    required: true
  openai-api-key:
    description: 'OpenAI API key'
    required: true
  github-token:
    description: 'GitHub token for API access'
    required: true
  model:
    description: 'OpenAI model to use'
    required: false
    default: 'o4-mini'
  custom-prompt:
    description: 'Custom system prompt for the AI'
    required: false
  max-turns:
    description: 'Maximum turns for the AI'
    required: false
    default: '30'


runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    OPENAI_API_KEY: ${{ inputs.openai-api-key }}
    GITHUB_TOKEN: ${{ inputs.github-token }}
    ACTION_TYPE: ${{ inputs.action-type }}
    MODEL: ${{ inputs.model }}
    CUSTOM_PROMPT: ${{ inputs.custom-prompt }}
    MAX_TURNS: ${{ inputs.max-turns }}