# Example workflow for AI code scanning

name: AI Code Scan

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly on Mondays
  workflow_dispatch:  # Allow manual triggering
  push:
    branches: [main]
    paths:
      - '**.py'
      - '**.js'
      - '**.ts'
      - '**.jsx'
      - '**.tsx'
      - '**.java'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: AI Code Scan
        id: scan
        uses: aguirreibarra/ai-github-action@main
        with:
          action-type: code-scan
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-files: 20
          include-patterns: "src/**/*.py,src/**/*.js,lib/**/*.ts"
          exclude-patterns: "**/__tests__/**,**/test/**,**/dist/**,**/node_modules/**"
