# Example workflow for AI issue analysis

name: AI Issue Analysis

on:
  issues:
    types: [opened, labeled]

jobs:
  analyze:
    runs-on: arc-runner-set
    if: github.event.action == 'opened' || contains(github.event.issue.labels.*.name, 'needs-triage')
    steps:
      - name: AI Issue Analysis
        uses: aguirreibarra/ai-github-action@main
        with:
          action-type: issue-analyze
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
