name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4


    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          version: "0.6.14"

    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Lint with ruff
      run: |
        make lint

    - name: Type check with mypy
      run: |
        make mypy

    - name: Test with pytest
      run: |
        make test

  # This job builds and tests the Docker image
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t ai-github-action .

    - name: Test Docker image
      run: |
        docker run --rm ai-github-action --help || true

  # This job runs the AI PR Review on itself
  ai-pr-review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: [test, docker]
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Self-review
      uses: ./
      with:
        action-type: pr-review
        openai-api-key: ${{ secrets.OPENAI_API_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        model: gpt-4o-mini
      env:
        LOG_LEVEL: INFO
